# Generated by Django 4.0.1 on 2022-01-17 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('portfolio', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('graduation', models.DateField(verbose_name='Graduation Date')),
                ('location', models.CharField(max_length=200)),
                ('degree', models.BooleanField(choices=[('BA', 'Bachelors of Arts'), ('BS', 'Bachelors of Science'), ('MA', 'Masters of Arts'), ('MS', 'Masters of Science'), ('CC', 'Certificate of Completion'), ('PH', 'PHD'), ('OT', 'Other')], default=False)),
                ('degree_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('project_date', models.DateField(verbose_name='Project Date')),
                ('technologies', models.TextField(max_length=800)),
                ('project_description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('L', 'Language'), ('F', 'Framework'), ('D', 'Database')], default='L', max_length=1)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ManyToManyField(to='main_app.Contact')),
                ('education', models.ManyToManyField(to='main_app.Education')),
                ('experience', models.ManyToManyField(to='main_app.Experience')),
                ('projects', models.ManyToManyField(to='main_app.Projects')),
                ('skills', models.ManyToManyField(to='main_app.Skill')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
