# Generated by Django 4.0.1 on 2022-01-19 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_resume_date_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('BA', 'Bachelors of Arts'), ('BS', 'Bachelors of Science'), ('MA', 'Masters of Arts'), ('MS', 'Masters of Science'), ('CC', 'Certificate of Completion'), ('PH', 'PHD'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 19, 22, 3, 1, 293754)),
        ),
    ]
