# Generated by Django 4.0.1 on 2022-01-20 01:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_contact_user_education_user_experience_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='Project Date')),
                ('technologies', models.TextField(max_length=800)),
                ('description', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 1, 17, 2, 11013)),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(to='main_app.Project'),
        ),
    ]
