# Generated by Django 4.0.1 on 2022-01-20 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_project_alter_resume_date_delete_projects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='contact',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='education',
            new_name='educations',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='experience',
            new_name='experiences',
        ),
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 18, 20, 58, 281699)),
        ),
    ]
